version: "3.9"

services:
  coreservice:
    build:
      context: .
      dockerfile: backend/Services/CoreService/Dockerfile
    image: coreservice 
    container_name: coreservice
    # ports: # <-- BỎ ĐI VÌ LÝ DO BẢO MẬT, CHỈ GIAO TIẾP QUA MẠNG NỘI BỘ
    #   - "5001:8080" 
    #   - "8443:8443"
    env_file:
      - ./backend/Services/CoreService/.env 
    environment:
      - ASPNETCORE_URLS=http://+:8080;https://+:8443
      - Kestrel__Certificates__Default__Path=/https/certs/parksmart.pfx
      - Kestrel__Certificates__Default__Password=TTt@192004
    volumes:
      - /etc/ssl/ocelot/parksmart.pfx:/https/certs/parksmart.pfx:ro
      - core_keys:/keys
    networks:
      - backend
    # MỚI: Thêm health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__whoami"] # Giả sử endpoint này tồn tại và nhẹ
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  parkingservice:
    build:
      context: ./backend/Services/parking-service 
      dockerfile: Dockerfile
    image: parkingservice
    container_name: parkingservice
    env_file:
      - ./backend/Services/parking-service/.env
    # ports: # <-- BỎ ĐI VÌ LÝ DO BẢO MẬT
    #   - "5000:5000"
    networks:
      - backend
    # MỚI: Thêm health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"] # Dùng endpoint gốc như đã thảo luận
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  ocelotgateway:
    build:
      context: .
      dockerfile: backend/Gateway/OcelotGateway/Dockerfile
    image: ocelotgateway
    container_name: ocelotgateway
    # MỚI: Nâng cấp depends_on
    depends_on:
      coreservice:
        condition: service_healthy # Chờ đến khi coreservice healthy
      parkingservice:
        condition: service_healthy # Chờ đến khi parkingservice healthy
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - /etc/ssl/ocelot/parksmart.pfx:/https/certs/parksmart.pfx:ro
    environment:
      - ASPNETCORE_URLS=http://+:8080;https://+:8443
      - Kestrel__Certificates__Default__Path=/https/certs/parksmart.pfx
      - Kestrel__Certificates__Default__Password=TTt@192004
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8443/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - backend 

volumes:
  core_keys:

networks:
  backend:
    driver: bridge