version: "3.9"

services:
  coreservice:
    build:
      context: .
      dockerfile: backend/Services/CoreService/Dockerfile
    container_name: coreservice
    ports:
      - "5001:80"
    networks:
      - backend

  parkingservice:
    build:
      context: .
      dockerfile: backend/Services/parking-service/Dockerfile   # ✅ đây mới là NodeJS
    container_name: parkingservice
    ports:
      - "5000:3000"
    networks:
      - backend

  ocelotgateway:
    build:
      context: .
      dockerfile: backend/Gateway/OcelotGateway/Dockerfile      # ✅ đây là .NET Gateway
    container_name: ocelotgateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - coreservice
      - parkingservice
    volumes:
      - ./certs:/https:ro
    networks:
      - backend


networks:
  backend:
    driver: bridge
