version: "3.9"

services:
  coreservice:
    build:
      context: .
      dockerfile: backend/Services/CoreService/Dockerfile
    image: coreservice 
    container_name: coreservice
    ports:
      - "5001:8080"
    networks:
      - backend

  parkingservice:
    build:
      context: ./backend/Services/parking-service 
      dockerfile: Dockerfile
    image: parkingservice
    container_name: parkingservice
    env_file:
      - .env
    ports:
      - "5000:3000"
    networks:
      - backend


  ocelotgateway:
    build:
      context: .
      dockerfile: backend/Gateway/OcelotGateway/Dockerfile
    image: ocelotgateway      # ✅ đây là .NET Gateway
    container_name: ocelotgateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - coreservice
      - parkingservice
    volumes:
      - ./certs:/https:ro
    networks:
      - backend


networks:
  backend:
    driver: bridge
