version: "3.9"

services:
  coreservice:
    build:
      context: ./backend/Services/CoreService
      dockerfile: Dockerfile
    image: coreservice 
    container_name: coreservice
    ports:
      - "5001:8080"
    networks:
      - backend

  parkingservice:
    build:
      context: ./backend/Services/parking-service
      dockerfile: Dockerfile
    image: parkingservice
    container_name: parkingservice
    env_file:
      - .env
    ports:
      - "5000:3000"
    networks:
      - backend

  ocelotgateway:
    build:
      context: ./backend/Gateway/OcelotGateway
      dockerfile: Dockerfile
    image: ocelotgateway
    container_name: ocelotgateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/https:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge
