version: "3.9"

services:
  coreservice:
    build:
      context: .
      dockerfile: backend/Services/CoreService/Dockerfile
    image: coreservice 
    container_name: coreservice
    ports:
      - "5001:8080"
    networks:
      - backend

  parkingservice:
    build:
      context: ./backend/Services/parking-service 
      dockerfile: Dockerfile
    image: parkingservice
    container_name: parkingservice
    env_file:
      - ./backend/Services/parking-service/.env
    ports:
      - "5000:5000"
    networks:
      - backend

  ocelotgateway:
    build:
      context: .
      dockerfile: backend/Gateway/OcelotGateway/Dockerfile
    image: ocelotgateway
    container_name: ocelotgateway
    depends_on:
      - coreservice
      - parkingservice
    ports:
      - "80:8080"
      - "443:8443"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]  # endpoint nhẹ
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - /etc/ssl/ocelot/ocelot.pfx:/https/certs/ocelot.pfx:ro
    environment:
      - ASPNETCORE_URLS=http://+:8080;https://+:8443
      - Kestrel__Certificates__Default__Path=/https/certs/ocelot.pfx
      - Kestrel__Certificates__Default__Password=123456
    networks:
      - backend    



networks:
  backend:
    driver: bridge
