/**
 * Định nghĩa vai trò nhận thông báo
 */
export enum NotificationRole {
  DRIVER = 'DRIVER',
  OPERATOR = 'OPERATOR',
  ADMIN = 'ADMIN',
}

/**
 * Định nghĩa loại thông báo (Dựa trên cột A từ file Excel)
 */
export enum NotificationType {
  // DRIVER
  BOOKING_SUCCESS = 'BOOKING_SUCCESS',
  BOOKING_FAILED = 'BOOKING_FAILED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  REMINDER_UPCOMING_2H = 'REMINDER_UPCOMING_2H',
  REMINDER_PARKING_STARTED = 'REMINDER_PARKING_STARTED',
  REMINDER_ENDING_15M = 'REMINDER_ENDING_15M',
  PARKING_TIME_ENDED = 'PARKING_TIME_ENDED',
  PARKING_EXTENDED_SUCCESS = 'PARKING_EXTENDED_SUCCESS',
  CHECKIN_SUCCESS = 'CHECKIN_SUCCESS',
  CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS',
  INVOICE_ISSUED = 'INVOICE_ISSUED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PROMOTION_INFO = 'PROMOTION_INFO',
  SUBSCRIPTION_ALERT = 'SUBSCRIPTION_ALERT',
  SUBSCRIPTION_PURCHASED = 'SUBSCRIPTION_PURCHASED',
  SUBSCRIPTION_EXTENDED_SUCCESS = 'SUBSCRIPTION_EXTENDED_SUCCESS',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  RESERVATION_REMINDER = 'RESERVATION_REMINDER',
  RESERVATION_PURCHASED = 'RESERVATION_PURCHASED',
  // PARKING LOT OPERATOR
  OPERATOR_NEW_BOOKING = 'OPERATOR_NEW_BOOKING',
  OPERATOR_VEHICLE_CHECKIN = 'OPERATOR_VEHICLE_CHECKIN',
  OPERATOR_VEHICLE_CHECKOUT = 'OPERATOR_VEHICLE_CHECKOUT',
  OPERATOR_BOOKING_CANCELLED = 'OPERATOR_BOOKING_CANCELLED',
  OPERATOR_VEHICLE_OVERSTAY = 'OPERATOR_VEHICLE_OVERSTAY',
  OPERATOR_LOT_FULL = 'OPERATOR_LOT_FULL',
  OPERATOR_REPORT_READY = 'OPERATOR_REPORT_READY',
  OPERATOR_SYSTEM_ALERT = 'OPERATOR_SYSTEM_ALERT',

  // CITY ADMIN
  ADMIN_SYSTEM_WIDE_ALERT = 'ADMIN_SYSTEM_WIDE_ALERT',
  ADMIN_OPERATOR_ISSUE = 'ADMIN_OPERATOR_ISSUE',
  ADMIN_AGGREGATE_REPORT_READY = 'ADMIN_AGGREGATE_REPORT_READY',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
}

/**
 * Định nghĩa event cho client (FE)
 */
export enum NotificationSocketEvents {
  /** Server gửi thông báo mới tới client */
  NEW_NOTIFICATION = 'newNotification',
  /** Client gửi thông báo đã kết nối và xác thực */
  IDENTITY = 'identity',
  /** Server gửi lỗi xác thực */
  AUTH_ERROR = 'authError',
}
